* My personal Emacs configuration
Hacking journey begins start from 2013.

It was written for Emacs 25.1+ on MacOS 10.11+

** How to use
Follow the install instruction here: https://github.com/zilongshanren/spacemacs#install ,
make sure your are using the fork repo: https://github.com/zilongshanren/spacemacs

Why use the forked repo?  What's the difference between the forked repo and the original repo?

*Nothing difference!*

The forked version is only a few commits behind the original repo, becuase sometimes the original repo can't functional well.

** What's the highlight of this configuration
1. It's a highly optimized Spacemacs configuration, you should use the configuration together with the *develop* branch of the officially Spacemacs.
2. I prefer to the =Ivy= completion interface, so I removed many helm related packages but keep the =helm-ag= package. The =counsel-ag= counterpart is not powerful as =helm-ag=.
3. I also removed some packages I don't have any chance to use. The complete list lies in the exclude section of the =init.el= file.
4. I also exclude the =Spaceline= package, cause it's easy to frozen the Emacs with this package enabled. So I create my own mode line configuration based on =Spaceline=.
5. The =Swiper= package sometimes frozen the Emacs UI when you split the window with very long lines. You could use `pkill -SIGUSR2 -i emacs` command line to break the frozen.

** Happing Hacking
This Emacs configuration is written for Emacs 25.1+ on Mac OS X 10.11+ and Linux Arch. Windows users may need to tweak the config for themselves.
1. Clone my configuration:
   #+BEGIN_SRC shell
     git clone https://github.com/ztlevi/spacemacs-config.git ~/.spacemacs.d
   #+END_SRC
2. Install all-the-icons fonts by ~M-x all-the-icons-install-fonts~. I'm using /Operator Mono Lig/ font(supports ligatures), you could change it under ~dotspacemacs-default-font~.
3. Language Server Protocol:
   #+BEGIN_SRC shell
     # cquery
     brew tap twlz0ne/homebrew-cquery
     brew install cquery

     # Javascript
     npm i -g javascript-typescript-langserver flow-language-server typescript-language-server typescript

     # python
     pip install python-language-server
   #+END_SRC

4. Dependencies needed
   - Install shellcheck, ispell, ripgrep, the_silver_searcher, the_platinum_searcher
     #+BEGIN_SRC shell
       brew install shellcheck coreutils ispell watchman gpg2
     #+END_SRC
   - npm
     #+BEGIN_SRC shell
       npm install -g prettier live-server import-js
     #+END_SRC
   - pip
     Make sure your ~python-shell-interpreter~ and pip is using the same environment (anaconda, python2 or python3). Check it with ~which -a pip ipython~
     #+BEGIN_SRC shell
       pip install yapf importmagic epc
     #+END_SRC
